[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true # Ensure SPA routing works correctly

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  
[dev]
  command = "npm run dev"
  targetPort = 5173

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://api.deepseek.com https://api.groq.com https://ai-dewey.netlify.app; img-src 'self' data: https://* blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval'; connect-src 'self' https://api.deepseek.com https://api.groq.com;"